- name: Ensure weather-ml-app Service exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: weather-ml-service
        namespace: "{{ weather_ml_namespace }}"
        labels:
          app: weather-ml-app
      spec:
        selector:
          app: weather-ml-app
        ports:
          - port: "{{ weather_ml_service_port | int }}"
            targetPort: "{{ weather_ml_container_port | int }}"
        type: "{{ weather_ml_service_type }}"
  tags: ansible_service
